/**
 * Text_fileDocument.java
 *
 * This file was generated by MapForce 2012r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.mapforce.Text_file;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.MappingException;
import com.altova.text.tablelike.Table;
import com.altova.text.tablelike.flf.Serializer;

public class Text_fileDocument extends Table
{
	protected ISerializer createSerializer()
	{
		Serializer result= new Serializer(this);
		result.getFormat().setAssumeRecordDelimitersPresent(true);
		result.getFormat().setFillCharacter(' ');
		result.getFormat().setRemoveEmpty(true);
		return result;
	}
	protected void initHeader(Header header)
	{
		
		header.add(new ColumnSpecification("Column13", 15));
		header.add(new ColumnSpecification("Column2", 60));
	}
	public Text_fileDocument() {}
}


